export const INIT_LOCALE = 'INIT_LOCALE';
export const GET_CURRENT_LOCATION_WEATHER_DATA = 'GET_CURRENT_LOCATION_WEATHER_DATA';
export const ADD_TO_MY_LOCATIONS = 'ADD_TO_MY_LOCATIONS';
export const DELETE_LOCATION = 'DELETE_LOCATION';
export const RETRY_CONNECTION = 'RETRY_CONNECTION';
export const ON_GET_CURRENT_LOCATION_WEATHER_DATA_RETRY = 'ON_GET_CURRENT_LOCATION_WEATHER_DATA_RETRY';